### ISSUE TITLE
Experience Button is not Working Inside the Footer and also the misspelled.

### ISSUE THREAD

**Issue by Satish-Ghode** [Satish-Ghode/PortFolio#2]
**Describe the bug**
When I clicked Experience button is not working, and also the misspelled.

**To Reproduce**
1. Go to 'Footer Section'
2. Click on 'Experience Button'

**Expected behavior**
when clicked on  Experience Button must be Redirected to Experience section or page 

**Screenshots**
![image](https://github.com/Satishghode/PortFolio/assets/88142229/3e5a57da-303a-49e0-b816-d4333b7d91f0)

**Comment by ShwetaDevv** [comment]
assign to me
